name: mlops-Brain_Tumor_Detection
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3

      - name: Install Jupyter Notebook
        run: |
          pip install jupyter

      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          jupyter nbconvert --execute --inplace Brain_Tumor_Detection.ipynb


